import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const year = new Date().getFullYear();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main className="flex-1">{children}</main>

        <footer className="border-t border-zinc-200 bg-white px-6 py-8 text-zinc-700 md:px-10">
          <div className="mx-auto grid w-full max-w-7xl gap-6 md:grid-cols-[auto_1fr] md:items-start">
            <Link href="/" className="inline-flex items-center">
              <Image
                src="/bachmann-logo.png"
                alt="Bachmann Haustechnik"
                width={180}
                height={68}
                className="h-auto w-[120px] md:w-[150px]"
              />
            </Link>

            <div className="grid gap-4 md:grid-cols-[1fr_auto_auto] md:items-start">
              <div>
                <p className="text-xs font-semibold tracking-[0.14em] text-zinc-500 uppercase">
                  Adresse
                </p>
                <p className="mt-2 text-sm leading-relaxed text-zinc-700">
                  Bachmann Haustechnik
                  <br />
                  Zugspitzstr. 4
                  <br />
                  82407 Wielenbach
                </p>
              </div>

              <div className="grid gap-2 text-sm font-semibold text-zinc-800">
                <p className="text-xs font-semibold tracking-[0.14em] text-zinc-500 uppercase">
                  Kontakt
                </p>
                <Link href="mailto:info@bachmann-haustechnik.de" className="transition hover:text-blue-700">
                  E-Mail schreiben
                </Link>
                <Link href="/kontakt" className="transition hover:text-blue-700">
                  Zum Formular
                </Link>
              </div>

              <div className="grid gap-2 text-sm font-semibold text-zinc-800 md:text-right">
                <p className="text-xs font-semibold tracking-[0.14em] text-zinc-500 uppercase">
                  Links
                </p>
                <Link href="/impressum" className="transition hover:text-blue-700">
                  Impressum
                </Link>
                <Link href="/datenschutz" className="transition hover:text-blue-700">
                  Datenschutzerklarung
                </Link>
              </div>
            </div>
          </div>

          <div className="mx-auto mt-6 flex w-full max-w-7xl flex-col gap-2 border-t border-zinc-200 pt-4 text-xs text-zinc-500 md:flex-row md:items-center md:justify-between">
            <p>© {year} Bachmann Haustechnik</p>
            <p className="inline-flex items-center gap-1.5">
              <span>Made with</span>
              <svg viewBox="0 0 24 24" className="h-4 w-4 text-rose-500" fill="currentColor" aria-hidden="true">
                <path d="M12 21.35 10.55 20.03C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09A6.02 6.02 0 0 1 16.5 3C19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35Z" />
              </svg>
              <span>by Efe Dolaman</span>
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
